### ISSUE TITLE
Add @apply 

### ISSUE THREAD

**Issue by Bowriverstudio** [gregsullivan/_tw-themejson#1]
Hi Greg, 

Well done on this project.

I use the tailwindcss color called sky-500 and would like to use it in my theme as info.

Currently, in the theme.json file, I write this.

```json
  {
                    "slug": "info",
                    "color": "#0ea5e9",
                    "name": "Info sky-500"
                }

```

I'd sooner write something like this.  

```json
  {
                    "slug": "info",
                    "color": "@apply sky-500",
                    "name": "Info"
  }

```

Any thoughts?

**Comment by gregsullivan** [comment]
Hello!

This is likely a documentation problem, but the intent is only to take values from `theme.json` and pass them to Tailwind. Because of that, the `theme.json` file needs to be one that will be accepted by and functional in WordPress without modification, and supporting `@apply` would prevent that.

Because these colors represent the subset of colors that will appear as options for users in the block editor, the sole goal is to reduce duplication to the extent that those colors need to be used elsewhere in the front-end design. (Redefining a color in the Tailwind configuration file will take precedence, so if you're dealing with a lot of shades, it might be easier just to define them all directly and manually maintain your `theme.json` file with an appropriate subset.)

Does that make sense?

**Comment by Bowriverstudio** [comment]
Yes, that makes perfect sense.  Thank you.
